/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        // Luxury Color Palette
        cream: '#F5EFE6',
        beige: '#DCCBB7',
        espresso: '#2A1D17',
        brown: '#6B4F3A',
        gold: '#B88A5A',
        maroon: '#6D3B3B',
        
        // Aliases for backward compatibility
        'primary-bg': '#F5EFE6',
        'dark-luxury': '#2A1D17',
        'warm-gold': '#B88A5A',
        'champagne': '#E8D3BE',
        'luxury-beige': '#DCCBB7',
        'white': '#FFFFFF',
        'success': '#3F7A57',
        'error': '#C62828',
        'bg': '#F5EFE6',
        'card': '#FFFFFF',
        'primary': '#2A1D17',
        'secondary': '#DCCBB7',
        'accent': '#B88A5A',
        'border': 'rgba(42,29,23,0.08)',
        'borderSubtle': 'rgba(42,29,23,0.06)',
        'shadow': 'rgba(42,29,23,0.06)',
        'black': '#000000',
        'textPrimary': '#2A1D17',
        'textSecondary': '#6B4F3A',
        'footerBlack': '#2A1D17',
        'footerText': '#F5EFE6',
        'darkBrown': '#2A1D17',
        'lightBeige': '#F5EFE6',
        'cream': '#F5EFE6',
        'bgPrimary': '#F5EFE6',
        'bgSecondary': '#DCCBB7',
        'textPrimaryDark': '#2A1D17',
        'cardCream': '#FFFFFF',
        'sidebar': '#2A1D17',
        'accentOrange': '#B88A5A',
        'softOrange': '#B88A5A',
        'linen': '#DCCBB7',
        'sand': '#DCCBB7',
        'stone': '#6B4F3A',
        'clay': '#B88A5A',
        'warm': '#8B7355',
        'warmBrown': '#6B4F3A',
        'elegantOrange': '#B88A5A',
        'orange': '#B88A5A',
        'inkPrimary': '#2A1D17',
        'inkSecondary': '#6B4F3A',
        'ink': '#2A1D17',
        'charcoal': '#2A1D17',
        'luxuryBeige': '#DCCBB7',
        'luxuryBeigeLight': '#F5EFE6',
        'luxuryBeigeSoft': '#FFFFFF',
        'warmBeige': '#DCCBB7',
        'warmBeigeLight': '#F5EFE6',
        'warmBeigeSoft': '#FFFFFF',
        'warning': '#B88A5A',
        'forest': '#2A1D17',
        'forestDark': '#1A1411',
        'forestLight': '#3D2D25',
        'bronze': '#B88A5A',
        'bronzeDark': '#9E754F',
        'bronzeLight': '#D4A87A',
        'creamDark': '#E8DCC8',
        'creamLight': '#FFFFFF',
        'charcoalLight': '#4A3A33',
        maroon: '#6D3B3B',
        maroonDark: '#5A2E2E',
        maroonLight: '#8B4E4E',
        espresso: '#2A1D17',
        espressoDark: '#1A1411',
        espressoLight: '#3D2D25',
        beige: '#DCCBB7',
        beigeLight: '#E8DCC8',
        beigeDark: '#C4B0A0',
        brown: '#6B4F3A',
        brownLight: '#8B6F5A',
        brownDark: '#4D3A2D',
        gold: '#B88A5A',
        goldDark: '#9E754F',
        goldLight: '#D4A87A',
      },
      fontFamily: {
        display: ['"Playfair Display"', '"Playfair Display Fallback"', 'Georgia', 'serif'],
        body: ['"Inter"', '"Inter Fallback"', 'system-ui', 'sans-serif'],
        sans: ['"Inter"', '"Inter Fallback"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        '2xs': ['0.65rem', { lineHeight: '1rem' }],
        '3xs': ['0.6rem', { lineHeight: '0.9rem' }],
      },
      letterSpacing: {
        widest: '0.25em',
        wider: '0.18em',
        wide: '0.12em',
      },
      boxShadow: {
        soft: '0 4px 24px rgba(42,29,23,0.05)',
        card: '0 2px 16px rgba(42,29,23,0.04)',
        lift: '0 12px 40px rgba(42,29,23,0.08)',
        innerSoft: 'inset 0 2px 8px rgba(42,29,23,0.02)',
        glow: '0 0 20px rgba(184,138,90,0.1)',
        cardHover: '0 10px 30px rgba(0,0,0,0.03)',
      },
      borderRadius: {
        '4xl': '2rem',
        '5xl': '2.5rem',
        '3xl': '1.5rem',
      },
      transitionTimingFunction: {
        smooth: 'cubic-bezier(0.4, 0, 0.2, 1)',
        luxury: 'cubic-bezier(0.22, 1, 0.36, 1)',
      },
      keyframes: {
        fadeUp: {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        slideInRight: {
          '0%': { opacity: '0', transform: 'translateX(20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        slideInMenu: {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        slideOutMenu: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(100%)' },
        },
        fadeInBackdrop: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
      },
      animation: {
        fadeUp: 'fadeUp 0.5s ease-out forwards',
        shimmer: 'shimmer 1.8s infinite linear',
        fadeIn: 'fadeIn 0.25s ease-out forwards',
        scaleIn: 'scaleIn 0.25s ease-out forwards',
        slideInRight: 'slideInRight 0.3s ease-out forwards',
        slideInMenu: 'slideInMenu 0.3s ease-out forwards',
        slideOutMenu: 'slideOutMenu 0.3s ease-out forwards',
        fadeInBackdrop: 'fadeInBackdrop 0.3s ease-out forwards',
      },
      backgroundImage: {
        'luxury-gradient': 'linear-gradient(135deg, #F5EFE6 0%, #DCCBB7 100%)',
        'card-gradient': 'linear-gradient(180deg, #FFFFFF 0%, #F5EFE6 100%)',
      },
    },
  },
  plugins: [],
}