/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#F7F2EA',
        secondary: '#F3ECE3',
        card: '#FFFDF8',
        textPrimary: '#2D241D',
        textSecondary: '#6B5A4A',
        accent: '#B67A4B',
        borderSubtle: 'rgba(45,36,29,0.08)',
        footerBlack: '#0B0B0B',
        footerText: '#FFFFFF',
        darkBrown: '#2D241D',
        lightBeige: '#F7F2EA',
        cream: '#FFFDF8',
        bgPrimary: '#F7F2EA',
        bgSecondary: '#F3ECE3',
        textPrimaryDark: '#2D241D',
        cardCream: '#FFFDF8',
        border: 'rgba(45,36,29,0.08)',
        sidebar: '#6B4E3D',
        accentOrange: '#B67A4B',
        softOrange: '#D4A373',
        borderBeige: 'rgba(45,36,29,0.08)',
        linen: '#F7F0E7',
        sand: '#E7D7C8',
        stone: '#B5A99A',
        clay: '#C4A882',
        warm: '#8B7355',
        warmBrown: '#6B4E3D',
        elegantOrange: '#B67A4B',
        orange: '#B67A4B',
        inkPrimary: '#2D241D',
        inkSecondary: '#6B5A4A',
        ink: '#2D241D',
        charcoal: '#3E2F25',
        white: '#FFFFFF',
        luxuryBeige: '#F3ECE3',
        luxuryBeigeLight: '#F7F2EA',
        luxuryBeigeSoft: '#FFFDF8',
        warmBeige: '#F3ECE3',
        warmBeigeLight: '#F7F2EA',
        warmBeigeSoft: '#FFFDF8',
        success: '#2E7D32',
        warning: '#B67A4B',
        error: '#D32F2F',
      },
      fontFamily: {
        display: ['"Playfair Display"', '"Playfair Display Fallback"', 'Georgia', 'serif'],
        body: ['"Inter"', '"Inter Fallback"', 'system-ui', 'sans-serif'],
        sans: ['"Inter"', '"Inter Fallback"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        '2xs': ['0.65rem', { lineHeight: '1rem' }],
        '3xs': ['0.6rem', { lineHeight: '0.9rem' }],
      },
      letterSpacing: {
        widest: '0.25em',
        wider: '0.18em',
        wide: '0.12em',
      },
      boxShadow: {
        soft: '0 4px 24px rgba(46,40,35,0.07)',
        card: '0 2px 16px rgba(46,40,35,0.06)',
        lift: '0 12px 40px rgba(46,40,35,0.12)',
        innerSoft: 'inset 0 2px 8px rgba(46,40,35,0.04)',
        glow: '0 0 20px rgba(182,122,75,0.15)',
        cardHover: '0 10px 30px rgba(0,0,0,0.04)',
      },
      borderRadius: {
        '4xl': '2rem',
        '5xl': '2.5rem',
        '3xl': '1.5rem',
      },
      transitionTimingFunction: {
        smooth: 'cubic-bezier(0.4, 0, 0.2, 1)',
        luxury: 'cubic-bezier(0.22, 1, 0.36, 1)',
      },
      keyframes: {
        fadeUp: {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        slideInRight: {
          '0%': { opacity: '0', transform: 'translateX(20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        slideInMenu: {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        slideOutMenu: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(100%)' },
        },
        fadeInBackdrop: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
      },
      animation: {
        fadeUp: 'fadeUp 0.5s ease-out forwards',
        shimmer: 'shimmer 1.8s infinite linear',
        fadeIn: 'fadeIn 0.25s ease-out forwards',
        scaleIn: 'scaleIn 0.25s ease-out forwards',
        slideInRight: 'slideInRight 0.3s ease-out forwards',
        slideInMenu: 'slideInMenu 0.3s ease-out forwards',
        slideOutMenu: 'slideOutMenu 0.3s ease-out forwards',
        fadeInBackdrop: 'fadeInBackdrop 0.3s ease-out forwards',
      },
      backgroundImage: {
        'luxury-gradient': 'linear-gradient(135deg, #F7F2EA 0%, #F3ECE3 100%)',
        'card-gradient': 'linear-gradient(180deg, #FFFFFF 0%, #FFFDF8 100%)',
      },
    },
  },
  plugins: [],
}
